CREATE DATABASE LOLJA;
USE LOLJA;
CREATE TABLE CLIENTES (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(29) NOT NULL,
	EMAIL VARCHAR(123) NOT NULL UNIQUE,
    DATA_CADASTRO DATE NOT NULL
);
CREATE TABLE PEDIDOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID INT NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
	DATA_PEDIDO DATE NOT NULL,
	VALOR_TOTAL DECIMAL NOT NULL
);

ALTER TABLE CLIENTES
ADD NUMERO VARCHAR(29);
ALTER TABLE PEDIDOS 
MODIFY COLUMN VALOR_TOTAL DECIMAL(10.2);
ALTER TABLE PEDIDOS RENAME COLUMN DATA_PEDIDO TO DATA;
DROP TABLE PEDIDOS; 
TRUNCATE TABLE CLIENTES;

CREATE TABLE PRODUTOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    PRECO DECIMAL NOT NULL
);
ALTER TABLE PRODUTOS
ADD CHECK (PRECO > 0);

ALTER TABLE CLIENTES
RENAME TO CLIENTES_ATIVOS;

SELECT * FROM CLIENTES;

