CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;
CREATE TABLE LIVROS(
	ID INT PRIMARY KEY NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    AUTOR VARCHAR(255) NOT NULL,
	PREÇO INT NOT NULL,
	ESTOQUE INT
);

INSERT INTO LIVROS (ID, TITULO, AUTOR, PREÇO, ESTOQUE) 
VALUES
(1, "COMO VIRAR UM DITADOR", "KIM JOHN UM", 100, 30),
(2, "MINECRAFT CRACKEADO ATUALIZADO 2025", "ENZO", 20, 7),
(3, "ONE PIECE", "ODA", 40, 1000),
(4, "666", "O DJABO", 66, 6),
(5, "COMO NÃO PROGRAMAR", "EU", 29, 1004);

UPDATE LIVROS
SET PREÇO = PREÇO*1.1
WHERE ID IN (1, 2 ,3);

UPDATE LIVROS 
SET ESTOQUE = 15
WHERE ID = 2;
UPDATE LIVROS 
SET ESTOQUE = 30
WHERE ID = 1;

UPDATE LIVROS 
SET ESTOQUE = 0
WHERE ID = 4;

DELETE FROM LIVROS
WHERE ESTOQUE = 0;

SELECT TITULO, AUTOR FROM LIVROS
WHERE PREÇO < 50;

SELECT * FROM LIVROS
WHERE ESTOQUE > 5;

SELECT TITULO, PREÇO FROM LIVROS
WHERE PREÇO = (SELECT MAX(PREÇO) FROM LIVROS);

DELETE FROM LIVROS
WHERE PREÇO > 99;